### PR TITLE
Circular hatch - choose center

### PR DESCRIPTION
**Pull request by mariana-s-fernandes**
Receive the position of circles' origin as input for circular hatching

Example 1: cirles' center outside of the image at (1.1, 1.1)
circular_skull

Example 2: circles' center inside the image at (0.2, 0.7)
circular_skull2

### CODE REVIEW

**Comment by mariana-s-fernandes** [comment]
Hi @abey79 , here is another one for you :) let me know if any changes are required

**Comment by abey79** [comment]
Thanks!

Btw, do you have a Twitter handle?

**Comment by mariana-s-fernandes** [comment]
No, I dont't have a twitter account (maybe I should). Why?

**Comment by abey79** [comment]
I just wanted to tweet about these changes and properly credit you :)

**Pull request merged**
